currency = (
    "Mirror of Kalandra",
    "Mirror Shard",
    "Awakener's Orb",
    "Hunter's Exalted Orb",
    "Crusader's Exalted Orb",
    "Warlord's Exalted Orb",
    "Redeemer's Exalted Orb",
    "Exalted Orb",
    "Blessing of Chayula",
    "Ancient Orb",
    "Divine Orb",
    "Orb of Annulment",
    "Fertile Catalyst",
    "Exalted Shard",
    "Prismatic Catalyst",
    "Harbinger's Orb",
    "Blessing of Uul-Netol",
    "Tempering Catalyst",
    "Awakened Sextant",
    "Annulment Shard",
    "Stacked Deck",
    "Blessing of Xoph",
    "Blessing of Tul",
    "Blessing of Esh",
    "Splinter of Chayula",
    "Gemcutter's Prism",
    "Prime Sextant",
    "Turbulent Catalyst",
    "Orb of Regret",
    "Orb of Horizons",
    "Simple Sextant",
    "Vaal Orb",
    "Regal Orb",
    "Orb of Fusing",
    "Cartographer's Chisel",
    "Abrasive Catalyst",
    "Intrinsic Catalyst",
    "Orb of Alchemy",
    "Orb of Scouring",
    "Orb of Binding",
    "Orb of Alteration",
    "Imbued Catalyst",
    "Silver Coin",
    "Blessed Orb",
    "Chromatic Orb",
    "Splinter of Uul-Netol",
    "Jeweller's Orb",
    "Glassblower's Bauble",
    "Orb of Augmentation",
    "Orb of Chance",
    "Engineer's Orb",
    "Splinter of Xoph",
    "Splinter of Tul",
    "Splinter of Esh",
    "Orb of Transmutation",
    "Portal Scroll",
    "Blacksmith's Whetstone",
    "Armourer's Scrap",
    "Perandus Coin",
    "Scroll of Wisdom",
)

fragments = (
    "Simulacrum",
    "Timeless Maraketh Emblem",
    "Chayula's Pure Breachstone",
    "Timeless Templar Emblem",
    "Uul-Netol's Pure Breachstone",
    "Chayula's Breachstone",
    "Fragment of Knowledge",
    "Fragment of Shape",
    "Gift to the Goddess",
    "Uul-Netol's Enriched Breachstone",
    "Tul's Pure Breachstone",
    "Xoph's Pure Breachstone",
    "Esh's Pure Breachstone",
    "Chayula's Enriched Breachstone",
    "Chayula's Charged Breachstone",
    "Uul-Netol's Charged Breachstone",
    "Timeless Vaal Emblem",
    "Uul-Netol's Breachstone",
    "Fragment of Eradication",
    "Fragment of Enslavement",
    "Fragment of Emptiness",
    "Fragment of the Chimera",
    "Xoph's Enriched Breachstone",
    "Tul's Enriched Breachstone",
    "Esh's Enriched Breachstone",
    "Fragment of Purification",
    "Fragment of Terror",
    "Fragment of Constriction",
    "Timeless Eternal Emblem",
    "Timeless Karui Emblem",
    "Fragment of the Hydra",
    "Fragment of the Phoenix",
    "Mortal Ignorance",
    "Tul's Breachstone",
    "Tul's Charged Breachstone",
    "Fragment of the Minotaur",
    "Yriel's Key",
    "Inya's Key",
    "Volkuur's Key",
    "Mortal Rage",
    "Mortal Hope",
    "Xoph's Charged Breachstone",
    "Esh's Charged Breachstone",
    "Tribute to the Goddess",
    "Dedication to the Goddess",
    "Xoph's Breachstone",
    "Eber's Key",
    "Esh's Breachstone",
    "Divine Vessel",
    "Mortal Grief",
    "Timeless Maraketh Splinter",
    "Timeless Templar Splinter",
    "Simulacrum Splinter",
    "Sacrifice at Midnight",
    "Offering to the Goddess",
    "Sacrifice at Noon",
    "Timeless Vaal Splinter",
    "Sacrifice at Dawn",
    "Sacrifice at Dusk",
    "Timeless Eternal Empire Splinter",
    "Timeless Karui Splinter",
)

delirium_orbs = (
    "Skittering Delirium Orb",
    "Blighted Delirium Orb",
    "Obscured Delirium Orb",
    "Fine Delirium Orb",
    "Fossilised Delirium Orb",
    "Diviner's Delirium Orb",
    "Foreboding Delirium Orb",
    "Thaumaturge's Delirium Orb",
    "Timeless Delirium Orb",
    "Cartographer's Delirium Orb",
    "Amorphous Delirium Orb",
    "Singular Delirium Orb",
    "Whispering Delirium Orb",
    "Imperial Delirium Orb",
    "Fragmented Delirium Orb",
    "Jeweller's Delirium Orb",
    "Abyssal Delirium Orb",
    "Portentous Delirium Orb",
    "Primal Delirium Orb",
    "Armoursmith's Delirium Orb",
    "Decadent Delirium Orb",
    "Blacksmith's Delirium Orb",
)

name_to_URL_dict = {
    currency: "https://poe.ninja/api/data/currencyoverview?league=Heist&type=Currency&language=en",
    fragments: "https://poe.ninja/api/data/currencyoverview?league=Heist&type=Fragment&language=en",
    delirium_orbs: "https://poe.ninja/api/data/itemoverview?league=Heist&type=DeliriumOrb&language=en",
}