currency = (
    "Mirror of Kalandra",
    "Mirror Shard",
    "Awakener's Orb",
    "Hunter's Exalted Orb",
    "Crusader's Exalted Orb",
    "Warlord's Exalted Orb",
    "Redeemer's Exalted Orb",
    "Exalted Orb",
    "Blessing of Chayula",
    "Ancient Orb",
    "Divine Orb",
    "Orb of Annulment",
    "Fertile Catalyst",
    "Exalted Shard",
    "Prismatic Catalyst",
    "Harbinger's Orb",
    "Blessing of Uul-Netol",
    "Tempering Catalyst",
    "Awakened Sextant",
    "Annulment Shard",
    "Stacked Deck",
    "Blessing of Xoph",
    "Blessing of Tul",
    "Blessing of Esh",
    "Splinter of Chayula",
    "Gemcutter's Prism",
    "Prime Sextant",
    "Turbulent Catalyst",
    "Orb of Regret",
    "Orb of Horizons",
    "Simple Sextant",
    "Vaal Orb",
    "Regal Orb",
    "Orb of Fusing",
    "Cartographer's Chisel",
    "Abrasive Catalyst",
    "Intrinsic Catalyst",
    "Orb of Alchemy",
    "Orb of Scouring",
    "Orb of Binding",
    "Orb of Alteration",
    "Imbued Catalyst",
    "Silver Coin",
    "Blessed Orb",
    "Chromatic Orb",
    "Splinter of Uul-Netol",
    "Jeweller's Orb",
    "Glassblower's Bauble",
    "Orb of Augmentation",
    "Orb of Chance",
    "Engineer's Orb",
    "Splinter of Xoph",
    "Splinter of Tul",
    "Splinter of Esh",
    "Orb of Transmutation",
    "Portal Scroll",
    "Blacksmith's Whetstone",
    "Armourer's Scrap",
    "Perandus Coin",
    "Scroll of Wisdom",
)

fragments = (
    "Simulacrum",
    "Timeless Maraketh Emblem",
    "Chayula's Pure Breachstone",
    "Timeless Templar Emblem",
    "Uul-Netol's Pure Breachstone",
    "Chayula's Breachstone",
    "Fragment of Knowledge",
    "Fragment of Shape",
    "Gift to the Goddess",
    "Uul-Netol's Enriched Breachstone",
    "Tul's Pure Breachstone",
    "Xoph's Pure Breachstone",
    "Esh's Pure Breachstone",
    "Chayula's Enriched Breachstone",
    "Chayula's Charged Breachstone",
    "Uul-Netol's Charged Breachstone",
    "Timeless Vaal Emblem",
    "Uul-Netol's Breachstone",
    "Fragment of Eradication",
    "Fragment of Enslavement",
    "Fragment of Emptiness",
    "Fragment of the Chimera",
    "Xoph's Enriched Breachstone",
    "Tul's Enriched Breachstone",
    "Esh's Enriched Breachstone",
    "Fragment of Purification",
    "Fragment of Terror",
    "Fragment of Constriction",
    "Timeless Eternal Emblem",
    "Timeless Karui Emblem",
    "Fragment of the Hydra",
    "Fragment of the Phoenix",
    "Mortal Ignorance",
    "Tul's Breachstone",
    "Tul's Charged Breachstone",
    "Fragment of the Minotaur",
    "Yriel's Key",
    "Inya's Key",
    "Volkuur's Key",
    "Mortal Rage",
    "Mortal Hope",
    "Xoph's Charged Breachstone",
    "Esh's Charged Breachstone",
    "Tribute to the Goddess",
    "Dedication to the Goddess",
    "Xoph's Breachstone",
    "Eber's Key",
    "Esh's Breachstone",
    "Divine Vessel",
    "Mortal Grief",
    "Timeless Maraketh Splinter",
    "Timeless Templar Splinter",
    "Simulacrum Splinter",
    "Sacrifice at Midnight",
    "Offering to the Goddess",
    "Sacrifice at Noon",
    "Timeless Vaal Splinter",
    "Sacrifice at Dawn",
    "Sacrifice at Dusk",
    "Timeless Eternal Empire Splinter",
    "Timeless Karui Splinter",
)

delirium_orbs = (
    "Skittering Delirium Orb",
    "Blighted Delirium Orb",
    "Obscured Delirium Orb",
    "Fine Delirium Orb",
    "Fossilised Delirium Orb",
    "Diviner's Delirium Orb",
    "Foreboding Delirium Orb",
    "Thaumaturge's Delirium Orb",
    "Timeless Delirium Orb",
    "Cartographer's Delirium Orb",
    "Amorphous Delirium Orb",
    "Singular Delirium Orb",
    "Whispering Delirium Orb",
    "Imperial Delirium Orb",
    "Fragmented Delirium Orb",
    "Jeweller's Delirium Orb",
    "Abyssal Delirium Orb",
    "Portentous Delirium Orb",
    "Primal Delirium Orb",
    "Armoursmith's Delirium Orb",
    "Decadent Delirium Orb",
    "Blacksmith's Delirium Orb",
)

watchstones = (
    "Booming Populace",
    "Booming Populace",
    "Misinformation",
    "Misinformation",
    "Booming Populace",
    "Misinformation",
    "Terror",
    "Misinformation",
    "War Among the Stars",
    "Terror",
    "Territories Unknown",
    "Stalwart Defenders",
    "Booming Populace",
    "War Among the Stars",
    "Booming Populace",
    "Booming Populace",
    "War Among the Stars",
    "Stalwart Defenders",
    "War Among the Stars",
    "War Among the Stars",
    "Misinformation",
    "Stalwart Defenders",
    "Booming Populace",
    "Stalwart Defenders",
    "Territories Unknown",
    "Stalwart Defenders",
    "Terror",
    "Terror",
    "Terror",
    "War Among the Stars",
    "Booming Populace",
    "Irresistable Temptation",
    "Terror",
    "Territories Unknown",
    "Booming Populace",
    "Terror",
    "Territories Unknown",
    "Booming Populace",
    "Misinformation",
    "Irresistable Temptation",
    "Irresistable Temptation",
    "War Among the Stars",
    "Territories Unknown",
    "Irresistable Temptation",
    "Booming Populace",
    "War Among the Stars",
    "Territories Unknown",
    "Stalwart Defenders",
    "Booming Populace",
    "War Among the Stars",
    "Irresistable Temptation",
    "Irresistable Temptation",
    "Terror",
    "Irresistable Temptation",
    "Booming Populace",
    "Territories Unknown",
    "Territories Unknown",
    "Stalwart Defenders",
    "Irresistable Temptation",
    "Territories Unknown",
    "Irresistable Temptation",
    "Territories Unknown",
    "War Among the Stars",
    "War Among the Stars",
    "Terror",
    "Territories Unknown",
    "Territories Unknown",
    "Stalwart Defenders",
    "Irresistable Temptation",
    "Territories Unknown",
    "Territories Unknown",
    "Irresistable Temptation",
    "Irresistable Temptation",
    "Territories Unknown",
    "Territories Unknown",
    "Territories Unknown",
    "Irresistable Temptation",
    "Irresistable Temptation",
    "Irresistable Temptation",
    "Irresistable Temptation",
    "Irresistable Temptation",
)

oils = (
    "Golden Oil",
    "Silver Oil",
    "Opalescent Oil",
    "Crimson Oil",
    "Black Oil",
    "Sepia Oil",
    "Verdant Oil",
    "Clear Oil",
    "Teal Oil",
    "Amber Oil",
    "Azure Oil",
    "Violet Oil",
    "Indigo Oil",
)

incubators = (
    "Time-Lost Incubator",
    "Thaumaturge's Incubator",
    "Geomancer's Incubator",
    "Ornate Incubator",
    "Diviner's Incubator",
    "Foreboding Incubator",
    "Fragmented Incubator",
    "Fine Incubator",
    "Fossilised Incubator",
    "Otherworldly Incubator",
    "Singular Incubator",
    "Primal Incubator",
    "Celestial Jeweller's Incubator",
    "Enchanted Incubator",
    "Cartographer's Incubator",
    "Skittering Incubator",
    "Abyssal Incubator",
    "Mysterious Incubator",
    "Celestial Armoursmith's Incubator",
    "Obscured Incubator",
    "Infused Incubator",
    "Decadent Incubator",
    "Celestial Blacksmith's Incubator",
    "Gemcutter's Incubator",
    "Whispering Incubator",
)

scarabs = (
    "Winged Reliquary Scarab",
    "Winged Divination Scarab",
    "Fenumal Lure",
    "Winged Breach Scarab",
    "Winged Legion Scarab",
    "Farric Lure",
    "Winged Harbinger Scarab",
    "Winged Sulphite Scarab",
    "Winged Ambush Scarab",
    "Craicic Lure",
    "Winged Cartography Scarab",
    "Winged Bestiary Scarab",
    "Winged Shaper Scarab",
    "Gilded Sulphite Scarab",
    "Winged Elder Scarab",
    "Gilded Breach Scarab",
    "Gilded Divination Scarab",
    "Gilded Legion Scarab",
    "Winged Metamorph Scarab",
    "Gilded Reliquary Scarab",
    "Saqawine Lure",
    "Polished Sulphite Scarab",
    "Gilded Harbinger Scarab",
    "Gilded Cartography Scarab",
    "Polished Legion Scarab",
    "Winged Perandus Scarab",
    "Rusted Sulphite Scarab",
    "Polished Breach Scarab",
    "Gilded Bestiary Scarab",
    "Gilded Ambush Scarab",
    "Rusted Legion Scarab",
    "Gilded Metamorph Scarab",
    "Winged Torment Scarab",
    "Polished Harbinger Scarab",
    "Polished Bestiary Scarab",
    "Gilded Elder Scarab",
    "Polished Cartography Scarab",
    "Polished Divination Scarab",
    "Polished Metamorph Scarab",
    "Rusted Reliquary Scarab",
    "Rusted Elder Scarab",
    "Rusted Breach Scarab",
    "Gilded Shaper Scarab",
    "Gilded Perandus Scarab",
    "Polished Elder Scarab",
    "Polished Ambush Scarab",
    "Rusted Metamorph Scarab",
    "Rusted Bestiary Scarab",
    "Rusted Divination Scarab",
    "Rusted Cartography Scarab",
    "Rusted Torment Scarab",
    "Rusted Ambush Scarab",
    "Rusted Shaper Scarab",
    "Rusted Perandus Scarab",
    "Rusted Harbinger Scarab",
    "Polished Shaper Scarab",
    "Gilded Torment Scarab",
    "Polished Torment Scarab",
    "Polished Perandus Scarab",
    "Polished Reliquary Scarab",
)

fossils = (
    "Fractured Fossil",
    "Faceted Fossil",
    "Bloodstained Fossil",
    "Bound Fossil",
    "Sanctified Fossil",
    "Corroded Fossil",
    "Hollow Fossil",
    "Shuddering Fossil",
    "Glyphic Fossil",
    "Perfect Fossil",
    "Gilded Fossil",
    "Enchanted Fossil",
    "Aetheric Fossil",
    "Jagged Fossil",
    "Prismatic Fossil",
    "Lucent Fossil",
    "Serrated Fossil",
    "Tangled Fossil",
    "Dense Fossil",
    "Aberrant Fossil",
    "Pristine Fossil",
    "Encrusted Fossil",
    "Frigid Fossil",
    "Scorched Fossil",
    "Metallic Fossil",
)

resonators = (
    "Prime Alchemical Resonator",
    "Prime Chaotic Resonator",
    "Powerful Chaotic Resonator",
    "Potent Chaotic Resonator",
    "Primitive Alchemical Resonator",
    "Potent Alchemical Resonator",
    "Powerful Alchemical Resonator",
    "Primitive Chaotic Resonator",
)

essences = (
    "Deafening Essence of Woe",
    "Essence of Horror",
    "Deafening Essence of Contempt",
    "Deafening Essence of Envy",
    "Deafening Essence of Greed",
    "Deafening Essence of Rage",
    "Deafening Essence of Zeal",
    "Deafening Essence of Loathing",
    "Deafening Essence of Scorn",
    "Deafening Essence of Sorrow",
    "Deafening Essence of Spite",
    "Deafening Essence of Dread",
    "Deafening Essence of Fear",
    "Deafening Essence of Wrath",
    "Essence of Delirium",
    "Shrieking Essence of Dread",
    "Shrieking Essence of Envy",
    "Shrieking Essence of Greed",
    "Shrieking Essence of Woe",
    "Shrieking Essence of Zeal",
    "Deafening Essence of Anger",
    "Deafening Essence of Hatred",
    "Deafening Essence of Misery",
    "Essence of Insanity",
    "Screaming Essence of Torment",
    "Shrieking Essence of Contempt",
    "Shrieking Essence of Rage",
    "Shrieking Essence of Sorrow",
    "Screaming Essence of Fear",
    "Screaming Essence of Sorrow",
    "Screaming Essence of Wrath",
    "Deafening Essence of Anguish",
    "Deafening Essence of Doubt",
    "Deafening Essence of Suffering",
    "Deafening Essence of Torment",
    "Essence of Hysteria",
    "Muttering Essence of Anger",
    "Muttering Essence of Contempt",
    "Muttering Essence of Fear",
    "Muttering Essence of Greed",
    "Muttering Essence of Hatred",
    "Muttering Essence of Sorrow",
    "Muttering Essence of Torment",
    "Muttering Essence of Woe",
    "Screaming Essence of Anger",
    "Screaming Essence of Anguish",
    "Screaming Essence of Contempt",
    "Screaming Essence of Doubt",
    "Screaming Essence of Dread",
    "Screaming Essence of Envy",
    "Screaming Essence of Greed",
    "Screaming Essence of Hatred",
    "Screaming Essence of Loathing",
    "Screaming Essence of Misery",
    "Screaming Essence of Rage",
    "Screaming Essence of Scorn",
    "Screaming Essence of Spite",
    "Screaming Essence of Suffering",
    "Screaming Essence of Woe",
    "Screaming Essence of Zeal",
    "Shrieking Essence of Anger",
    "Shrieking Essence of Anguish",
    "Shrieking Essence of Doubt",
    "Shrieking Essence of Fear",
    "Shrieking Essence of Hatred",
    "Shrieking Essence of Loathing",
    "Shrieking Essence of Misery",
    "Shrieking Essence of Scorn",
    "Shrieking Essence of Spite",
    "Shrieking Essence of Suffering",
    "Shrieking Essence of Torment",
    "Shrieking Essence of Wrath",
    "Wailing Essence of Anger",
    "Wailing Essence of Anguish",
    "Wailing Essence of Contempt",
    "Wailing Essence of Doubt",
    "Wailing Essence of Fear",
    "Wailing Essence of Greed",
    "Wailing Essence of Hatred",
    "Wailing Essence of Loathing",
    "Wailing Essence of Rage",
    "Wailing Essence of Sorrow",
    "Wailing Essence of Spite",
    "Wailing Essence of Suffering",
    "Wailing Essence of Torment",
    "Wailing Essence of Woe",
    "Wailing Essence of Wrath",
    "Wailing Essence of Zeal",
    "Weeping Essence of Anger",
    "Weeping Essence of Contempt",
    "Weeping Essence of Doubt",
    "Weeping Essence of Fear",
    "Weeping Essence of Greed",
    "Weeping Essence of Hatred",
    "Weeping Essence of Rage",
    "Weeping Essence of Sorrow",
    "Weeping Essence of Suffering",
    "Weeping Essence of Torment",
    "Weeping Essence of Woe",
    "Weeping Essence of Wrath",
    "Whispering Essence of Contempt",
    "Whispering Essence of Greed",
    "Whispering Essence of Hatred",
    "Whispering Essence of Woe",
    "Remnant of Corruption",
)

divination_cards = (
    "House of Mirrors",
    "The Doctor",
    "Unrequited Love",
    "The Demon",
    "The Fiend",
    "Brother's Stash",
    "Gift of Asenath",
    "The Cheater",
    "Beauty Through Death",
    "Nook's Crown",
    "The Immortal",
    "Succor of the Sinless",
    "Alluring Bounty",
    "The Nurse",
    "The Samurai's Eye",
    "Immortal Resolve",
    "Desecrated Virtue",
    "The Craving",
    "Abandoned Wealth",
    "Seven Years Bad Luck",
    "Pride of the First Ones",
    "The Iron Bard",
    "The Long Con",
    "The Dragon's Heart",
    "The Progeny of Lunaris",
    "Wealth and Power",
    "The White Knight",
    "Azyran's Reward",
    "The Sustenance",
    "The Price of Loyalty",
    "The Saint's Treasure",
    "The Soul",
    "The Greatest Intentions",
    "The Eye of Terror",
    "The Escape",
    "The Gulf",
    "Hunter's Reward",
    "The World Eater",
    "The Primordial",
    "The Damned",
    "The Hive of Knowledge",
    "The Betrayal",
    "Squandered Prosperity",
    "The Strategist",
    "The Bitter Blossom",
    "The Artist",
    "The Enlightened",
    "The Spark and the Flame",
    "The Bargain",
    "Council of Cats",
    "The Mayor",
    "Chaotic Disposition",
    "The Hoarder",
    "The Offering",
    "The Sephirot",
    "Dark Dreams",
    "Void of the Elements",
    "Peaceful Moments",
    "The Academic",
    "The Queen",
    "Remembrance",
    "Etched in Blood",
    "The Eldritch Decay",
    "A Familiar Call",
    "Pride Before the Fall",
    "The Cartographer",
    "The Celestial Justicar",
    "The Polymath",
    "The Wolven King's Bite",
    "Rebirth",
    "Blessing of God",
    "The Undaunted",
    "The Celestial Stone",
    "The Life Thief",
    "The Awakened",
    "Triskaidekaphobia",
    "Unchained",
    "Loyalty",
    "Mawr Blaidd",
    "The Brittle Emperor",
    "The Cursed King",
    "The Dapper Prodigy",
    "The Ethereal",
    "The Gemcutter",
    "The King's Heart",
    "The Risk",
    "The Valkyrie",
    "The Vast",
    "The Void",
    "Time-Lost Relic",
    "The Breach",
    "The Hale Heart",
    "The Professor",
    "The Innocent",
    "Boon of the First Ones",
    "The Sacrifice",
    "The Landing",
    "Burning Blood",
    "The Heroic Shot",
    "The Old Man",
    "Divine Justice",
    "The Fishmonger",
    "A Note in the Wind",
    "The Catalyst",
    "The Master Artisan",
    "The Porcupine",
    "Underground Forest",
    "The Doppelganger",
    "A Mother's Parting Gift",
    "Anarchy's Price",
    "Assassin's Favour",
    "Audacity",
    "Blind Venture",
    "Boundless Realms",
    "Bowyer's Dream",
    "Cartographer's Delight",
    "Coveted Possession",
    "Death",
    "Destined to Crumble",
    "Dialla's Subjugation",
    "Doedre's Madness",
    "Earth Drinker",
    "Emperor of Purity",
    "Emperor's Luck",
    "Gemcutter's Promise",
    "Gift of the Gemling Queen",
    "Glimmer of Hope",
    "Grave Knowledge",
    "Her Mask",
    "Heterochromia",
    "Hope",
    "Hubris",
    "Humility",
    "Hunter's Resolve",
    "Jack in the Box",
    "Lantador's Lost Love",
    "Last Hope",
    "Light and Truth",
    "Lost Worlds",
    "Lucky Connections",
    "Lucky Deck",
    "Lysah's Respite",
    "Merciless Armament",
    "Prosperity",
    "Rain of Chaos",
    "Rain Tempter",
    "Rats",
    "Scholar of the Seas",
    "Shard of Fate",
    "The Aesthete",
    "The Arena Champion",
    "The Avenger",
    "The Battle Born",
    "The Body",
    "The Calling",
    "The Carrion Crow",
    "The Cataclysm",
    "The Chains that Bind",
    "The Conduit",
    "The Dark Mage",
    "The Demoness",
    "The Dragon",
    "The Drunken Aristocrat",
    "The Encroaching Darkness",
    "The Endurance",
    "The Explorer",
    "The Feast",
    "The Fletcher",
    "The Flora's Gift",
    "The Formless Sea",
    "The Fox",
    "The Gambler",
    "The Gentleman",
    "The Gladiator",
    "The Harvester",
    "The Hermit",
    "The Hunger",
    "The Incantation",
    "The Inoculated",
    "The Inventor",
    "The Jester",
    "The King's Blade",
    "The Last One Standing",
    "The Lich",
    "The Lion",
    "The Lord in Black",
    "The Lover",
    "The Lunaris Priestess",
    "The Mercenary",
    "The Metalsmith's Gift",
    "The Oath",
    "The One With All",
    "The Pack Leader",
    "The Pact",
    "The Penitent",
    "The Poet",
    "The Rabid Rhoa",
    "The Road to Power",
    "The Scarred Meadow",
    "The Scavenger",
    "The Scholar",
    "The Sigil",
    "The Siren",
    "The Spoiled Prince",
    "The Stormcaller",
    "The Summoner",
    "The Sun",
    "The Surgeon",
    "The Surveyor",
    "The Survivalist",
    "The Thaumaturgist",
    "The Throne",
    "The Tower",
    "The Traitor",
    "The Trial",
    "The Twins",
    "The Tyrant",
    "The Union",
    "The Visionary",
    "The Warden",
    "The Warlord",
    "The Watcher",
    "The Web",
    "The Wind",
    "The Wolf",
    "The Wolf's Shadow",
    "The Wrath",
    "Three Faces in the Dark",
    "Thunderous Skies",
    "Tranquillity",
    "Treasure Hunter",
    "Turn the Other Cheek",
    "Vinia's Token",
    "Volatile Power",
    "Mitts",
    "The Valley of Steel Boxes",
    "Call to the First Ones",
    "The Wretched",
    "Lingering Remnants",
    "The Coming Storm",
    "The Wolverine",
    "The Garish Power",
    "The Standoff",
    "The Forsaken",
    "Might is Right",
    "Atziri's Arsenal",
    "The Opulent",
    "Struck by Lightning",
    "The Blazing Fire",
    "The Ruthless Ceinture",
    "No Traces",
    "The Eye of the Dragon",
    "The Realm",
    "Left to Fate",
    "The Obscured",
    "The Deceiver",
    "The Puzzle",
    "The Insatiable",
    "Forbidden Power",
    "The Dreamer",
    "Three Voices",
    "The Jeweller's Boon",
    "The Army of Blood",
    "The Beast",
    "Perfection",
    "The Sword King's Salute",
    "The Master",
    "The Fathomless Depths",
    "The Rite of Elements",
    "The Dreamland",
    "The Admirer",
    "The Witch",
    "The Darkest Dream",
    "The Undisputed",
    "Harmony of Souls",
    "The Twilight Moon",
    "The Wilted Rose",
    "The Endless Darkness",
    "The Price of Protection",
    "The Cacophony",
    "A Dab of Ink",
    "Sambodhi's Vow",
    "Arrogance of the Vaal",
    "The Mad King",
    "Alone in the Darkness",
    "The Lord of Celebration",
    "Dark Temptation",
    "The Journey",
    "The Messenger",
    "Monochrome",
    "The Golden Era",
    "Boon of Justice",
    "The Seeker",
    "Vanity",
    "Thirst for Knowledge",
    "Imperial Legacy",
    "Echoes of Love",
    "The Deep Ones",
    "The Fool",
    "Demigod's Wager",
    "Buried Treasure",
    "The Archmage's Right Hand",
    "The Mountain",
    "The Skeleton",
    "Akil's Prophecy",
    "The Wolf's Legacy",
    "The Deal",
    "The Side Quest",
    "More is Never Enough",
    "Cameria's Cut",
    "The Bones",
    "Friendship",
    "The Chosen",
    "Baited Expectations",
    "Deathly Designs",
    "The Tinkerer's Table",
    "The Easy Stroll",
    "Prometheus' Armoury",
    "The Tumbleweed",
    "The Unexpected Prize",
    "The Journalist",
    "The Cache",
    "Cursed Words",
    "Vile Power",
)

get_value_dict = {
    "chaosValue": (
        delirium_orbs
        + watchstones
        + oils
        + incubators
        + scarabs
        + fossils
        + resonators
        + essences
        + divination_cards
    ),
    "pay_value": (currency + fragments),
}

name_to_URL_dict = {
    currency: "https://poe.ninja/api/data/currencyoverview?league=Heist&type=Currency&language=en",
    fragments: "https://poe.ninja/api/data/currencyoverview?league=Heist&type=Fragment&language=en",
    delirium_orbs: "https://poe.ninja/api/data/itemoverview?league=Heist&type=DeliriumOrb&language=en",
    watchstones: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Watchstone&language=en",
    oils: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Oil&language=en",
    incubators: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Incubator&language=en",
    scarabs: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Scarab&language=en",
    fossils: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Fossil&language=en",
    resonators: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Resonator&language=en",
    essences: "https://poe.ninja/api/data/itemoverview?league=Heist&type=Essence&language=en",
    divination_cards: "https://poe.ninja/api/data/itemoverview?league=Heist&type=DivinationCard&language=en",
}